### GET request to example server
GET http://localhost:3000/

###

###
POST http://localhost:3000/recipe
Content-Type: application/json

{
  "nazwa":"kmkmkmkmka",
  "ingredients":["kmjikm"],
  "instruction":"kmkmkmkmkk",
  "rate":4
}
###

###
PUT http://localhost:3000/recipe/6771921483b0ca4c7782349c
Content-Type: application/json

{
  "nazwa":"hh",
  "ingredients":["asdsaadssd","dssdadds","kadjsdaskjadd"],
  "instruction":"hhh",
  "rate":1
}
###

###
DELETE localhost:3000/recipe/6771921483b0ca4c7782349c
Content-Type: application/json
###